docs_dir: docs/book
site_dir: docs/html
extra:
  project: Packages
  current_version: v4
  versions:
    - v4
nav:
  - Home: index.md
  - v4:
      - Overview: v4/overview.md
      - Installation: v4/installation.md
      - Configuration: v4/configuration.md
      - Usage: v4/usage.md
      - Transports: v4/transports.md
site_name: dot-mail
site_description: "DotKernel's mail service"
repo_url: "https://github.com/dotkernel/dot-mail"
plugins:
  - search
